# Generated by Django 5.2 on 2025-04-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='not_answer',
            field=models.TextField(blank=True),
        ),
    ]
