# Generated by Django 5.2 on 2025-04-28 23:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0002_version_not_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
