# Generated by Django 5.2 on 2025-04-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0003_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
