# Generated by Django 5.2 on 2025-04-29 12:53

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0004_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='also_answer',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='answer',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='commentary',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='not_answer',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='sources',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='text',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
