# Generated by Django 5.2 on 2025-04-29 12:59

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0005_alter_version_also_answer_alter_version_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='commentary',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='sources',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
