# Generated by Django 5.2 on 2025-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0006_alter_version_commentary_alter_version_sources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='also_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='not_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='sources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='text',
            field=models.TextField(),
        ),
    ]
