# Generated by Django 5.2 on 2025-04-29 13:09

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0007_alter_version_also_answer_alter_version_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='answer',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
