# Generated by Django 5.2 on 2025-04-29 13:11

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0008_alter_version_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='also_answer',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='commentary',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='not_answer',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='sources',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
