# Generated by Django 5.2 on 2025-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0009_alter_version_also_answer_alter_version_commentary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='razdatka',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
