# Generated by Django 5.2 on 2025-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0015_alter_version_razdatka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='razdatka',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
