# Generated by Django 5.2 on 2025-04-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0016_alter_version_razdatka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='razdatka',
            field=models.ImageField(blank=True, upload_to='my_questions/static/my_questions/uploads/'),
        ),
    ]
