# Generated by Django 5.2 on 2025-04-29 22:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0017_alter_version_razdatka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
