# Generated by Django 5.2 on 2025-04-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0018_alter_version_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AddField(
            model_name='test',
            name='version',
            field=models.ManyToManyField(to='my_questions.version'),
        ),
    ]
