# Generated by Django 5.2 on 2025-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0019_remove_test_question_test_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='rating_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
