# Generated by Django 5.2 on 2025-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0020_tester_rating_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tester',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AddField(
            model_name='tester',
            name='patronymic',
            field=models.CharField(blank=True, null=True),
        ),
    ]
