# Generated by Django 5.2 on 2025-04-30 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0021_alter_tester_options_tester_patronymic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tester',
            name='test',
            field=models.ManyToManyField(blank=True, to='my_questions.test'),
        ),
    ]
