# Generated by Django 5.2 on 2025-04-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0022_tester_user_alter_tester_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
