# Generated by Django 5.2 on 2025-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0023_test_description_alter_test_date_alter_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tester',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='testers', to='my_questions.test'),
        ),
    ]
