# Generated by Django 5.2 on 2025-04-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0024_alter_tester_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-created']},
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_questions.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_questions.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=models.ManyToManyField(through='my_questions.TestQuestion', to='my_questions.question'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_test_question'),
        ),
    ]
