# Generated by Django 5.2 on 2025-05-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0025_alter_version_options_testquestion_test_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order']},
        ),
    ]
