# Generated by Django 5.2 on 2025-05-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0026_alter_testquestion_options'),
    ]

    operations = [

    ]
