# Generated by Django 5.2 on 2025-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0027_alter_version_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='text',
            field=models.TextField(),
        ),
    ]
