# Generated by Django 5.2 on 2025-05-01 17:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0028_alter_version_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
