# Generated by Django 5.2 on 2025-05-01 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0030_alter_version_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 1, 22, 49, 7, 152889, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
