# Generated by Django 5.2 on 2025-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0031_version_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
