# Generated by Django 5.2 on 2025-05-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0032_alter_version_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='committed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
