# Generated by Django 5.2 on 2025-05-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0033_test_comments_test_committed_test_committed_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='comments',
        ),
    ]
