# Generated by Django 5.2 on 2025-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0034_remove_test_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
