# Generated by Django 5.2 on 2025-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0035_test_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='comments',
            new_name='editor_comments',
        ),
        migrations.AddField(
            model_name='version',
            name='editor_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
