# Generated by Django 5.2 on 2025-05-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0036_rename_comments_test_editor_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='comments',
        ),
    ]
