# Generated by Django 5.2 on 2025-05-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_questions', '0037_remove_version_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='is_answered',
            field=models.CharField(blank=True, choices=[('AM', 'Ответили в минуте'), ('AN', 'Ответили'), ('AH', 'Оветили с подсказкой'), ('NA', 'Не ответили'), ('NK', 'Нет свояка')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.ManyToManyField(related_name='tests', through='my_questions.TestQuestion', to='my_questions.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='version',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='my_questions.version'),
        ),
    ]
